-- Oracle 11g Schema for ChainFlow SCM

-- ==========================================
-- 1. DROP EXISTING TABLES (To allow re-running)
-- ==========================================
BEGIN
   FOR cur_rec IN (SELECT table_name FROM user_tables WHERE table_name IN (
       'APP_USERS', 'OVERNIGHT_SHIP', 'DAY_SHIP', 'SHIPMENT', 'INCLUDE', 'ORDERS', 
       'PRODUCTS', 'LOGISTICS_PROVIDERS', 'GENERAL_WAREHOUSE', 'COLD_WAREHOUSE', 
       'WAREHOUSES', 'RETAILERS', 'SUPPLIERS', 'PERSON'
   ))
   LOOP
      EXECUTE IMMEDIATE 'DROP TABLE ' || cur_rec.table_name || ' CASCADE CONSTRAINTS';
   END LOOP;
END;
/

-- ==========================================
-- 2. CREATE TABLES (Based strictly on EERD)
-- ==========================================

-- System Users (For login dashboard)
CREATE TABLE APP_USERS (
    USERNAME VARCHAR2(50) PRIMARY KEY,
    PASSWORD VARCHAR2(255) NOT NULL,
    USER_ROLE VARCHAR2(20) CHECK (USER_ROLE IN ('admin', 'user')) NOT NULL
);

-- PERSON Hierarchy
CREATE TABLE PERSON (
    PERSON_ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL,
    ADDRESS VARCHAR2(255),
    COUNTRY VARCHAR2(50),
    PHONE_NUMBER VARCHAR2(20),
    EMAIL VARCHAR2(100),
    PERSON_TYPE VARCHAR2(10) CHECK (PERSON_TYPE IN ('SUPPLIER', 'RETAILER')) NOT NULL
);

CREATE TABLE SUPPLIERS (
    SUPPLIER_ID NUMBER PRIMARY KEY,
    PERSON_ID NUMBER UNIQUE NOT NULL,
    CONSTRAINT FK_SUPPLIER_PERSON FOREIGN KEY (PERSON_ID) REFERENCES PERSON(PERSON_ID)
);

CREATE TABLE RETAILERS (
    RETAILER_ID NUMBER PRIMARY KEY,
    PERSON_ID NUMBER UNIQUE NOT NULL,
    CONSTRAINT FK_RETAILER_PERSON FOREIGN KEY (PERSON_ID) REFERENCES PERSON(PERSON_ID)
);

-- WAREHOUSE Hierarchy
CREATE TABLE WAREHOUSES (
    WAREHOUSE_ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL,
    LOCATION VARCHAR2(255),
    MANAGER_NAME VARCHAR2(100),
    CAPACITY NUMBER,
    WAREHOUSE_TYPE VARCHAR2(10) CHECK (WAREHOUSE_TYPE IN ('COLD', 'GENERAL')) NOT NULL
);

CREATE TABLE COLD_WAREHOUSE (
    WAREHOUSE_ID NUMBER PRIMARY KEY,
    COOLING_SYSTEM_ID VARCHAR2(50),
    CONSTRAINT FK_COLD_WH FOREIGN KEY (WAREHOUSE_ID) REFERENCES WAREHOUSES(WAREHOUSE_ID)
);

CREATE TABLE GENERAL_WAREHOUSE (
    WAREHOUSE_ID NUMBER PRIMARY KEY,
    LAYOUT_STRUCTURE VARCHAR2(100),
    CONSTRAINT FK_GEN_WH FOREIGN KEY (WAREHOUSE_ID) REFERENCES WAREHOUSES(WAREHOUSE_ID)
);

-- LOGISTICS
CREATE TABLE LOGISTICS_PROVIDERS (
    PROVIDER_ID NUMBER PRIMARY KEY,
    COMPANY_NAME VARCHAR2(100) NOT NULL,
    TRANSPORT_MODE VARCHAR2(50),
    AREA VARCHAR2(100),
    CONTACT_NUMBER VARCHAR2(20)
);

-- PRODUCTS
CREATE TABLE PRODUCTS (
    PRODUCT_ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL,
    STOCK_QUANTITY NUMBER DEFAULT 0,
    PRICE NUMBER(10, 2),
    SUPPLIER_ID NUMBER,
    WAREHOUSE_ID NUMBER,
    CONSTRAINT FK_PROD_SUPPLIER FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIERS(SUPPLIER_ID),
    CONSTRAINT FK_PROD_WAREHOUSE FOREIGN KEY (WAREHOUSE_ID) REFERENCES WAREHOUSES(WAREHOUSE_ID)
);

-- ORDERS
CREATE TABLE ORDERS (
    ORDER_ID NUMBER PRIMARY KEY,
    ORDER_DATE DATE DEFAULT SYSDATE,
    BILL NUMBER(10, 2),
    RETAILER_ID NUMBER,
    CONSTRAINT FK_ORDER_RETAILER FOREIGN KEY (RETAILER_ID) REFERENCES RETAILERS(RETAILER_ID)
);

-- INCLUDE (M:N Products to Orders)
CREATE TABLE INCLUDE (
    PRODUCT_ID NUMBER,
    ORDER_ID NUMBER,
    ITEM_QUANTITY NUMBER NOT NULL,
    PRIMARY KEY (PRODUCT_ID, ORDER_ID),
    CONSTRAINT FK_INC_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID),
    CONSTRAINT FK_INC_ORDER FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID)
);

-- SHIPMENT Hierarchy
CREATE TABLE SHIPMENT (
    SHIPMENT_ID NUMBER PRIMARY KEY,
    TRACKING_NUMBER VARCHAR2(50) UNIQUE,
    SHIPMENT_DATE DATE,
    DELIVERY_DATE DATE,
    STATUS VARCHAR2(50),
    WAREHOUSE_ID NUMBER,
    PROVIDER_ID NUMBER,
    ORDER_ID NUMBER,
    PRODUCT_ID NUMBER,
    SHIPMENT_TYPE VARCHAR2(10) CHECK (SHIPMENT_TYPE IN ('DAY', 'OVERNIGHT')) NOT NULL,
    CONSTRAINT FK_SHIP_WAREHOUSE FOREIGN KEY (WAREHOUSE_ID) REFERENCES WAREHOUSES(WAREHOUSE_ID),
    CONSTRAINT FK_SHIP_PROVIDER FOREIGN KEY (PROVIDER_ID) REFERENCES LOGISTICS_PROVIDERS(PROVIDER_ID),
    CONSTRAINT FK_SHIP_ORDER FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID),
    CONSTRAINT FK_SHIP_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID)
);

CREATE TABLE DAY_SHIP (
    SHIPMENT_ID NUMBER PRIMARY KEY,
    PREFERRED_WINDOW VARCHAR2(50),
    CONSTRAINT FK_DAY_SHIP FOREIGN KEY (SHIPMENT_ID) REFERENCES SHIPMENT(SHIPMENT_ID)
);

CREATE TABLE OVERNIGHT_SHIP (
    SHIPMENT_ID NUMBER PRIMARY KEY,
    SPECIAL_FEE NUMBER(10,2),
    CONSTRAINT FK_NIGHT_SHIP FOREIGN KEY (SHIPMENT_ID) REFERENCES SHIPMENT(SHIPMENT_ID)
);

-- ==========================================
-- 3. INSERT MOCK DATA
-- ==========================================

-- Users
INSERT INTO APP_USERS (USERNAME, PASSWORD, USER_ROLE) VALUES ('admin', 'admin123', 'admin');
INSERT INTO APP_USERS (USERNAME, PASSWORD, USER_ROLE) VALUES ('operator', 'user123', 'user');

-- Persons
INSERT INTO PERSON (PERSON_ID, NAME, COUNTRY, PERSON_TYPE) VALUES (1, 'Tech Supplies Inc.', 'USA', 'SUPPLIER');
INSERT INTO PERSON (PERSON_ID, NAME, COUNTRY, PERSON_TYPE) VALUES (2, 'Global Electronics', 'UK', 'SUPPLIER');
INSERT INTO PERSON (PERSON_ID, NAME, COUNTRY, PERSON_TYPE) VALUES (3, 'MegaMart Store', 'USA', 'RETAILER');

-- Suppliers/Retailers
INSERT INTO SUPPLIERS (SUPPLIER_ID, PERSON_ID) VALUES (101, 1);
INSERT INTO SUPPLIERS (SUPPLIER_ID, PERSON_ID) VALUES (102, 2);
INSERT INTO RETAILERS (RETAILER_ID, PERSON_ID) VALUES (201, 3);

-- Warehouses
INSERT INTO WAREHOUSES (WAREHOUSE_ID, NAME, LOCATION, CAPACITY, WAREHOUSE_TYPE) VALUES (1, 'North Central Hub', 'Chicago, IL', 5000, 'GENERAL');
INSERT INTO GENERAL_WAREHOUSE (WAREHOUSE_ID, LAYOUT_STRUCTURE) VALUES (1, 'Aisle/Rack standard');

INSERT INTO WAREHOUSES (WAREHOUSE_ID, NAME, LOCATION, CAPACITY, WAREHOUSE_TYPE) VALUES (2, 'West Cold Storage', 'Seattle, WA', 2000, 'COLD');
INSERT INTO COLD_WAREHOUSE (WAREHOUSE_ID, COOLING_SYSTEM_ID) VALUES (2, 'FREON-9X');

-- Logistics
INSERT INTO LOGISTICS_PROVIDERS (PROVIDER_ID, COMPANY_NAME, TRANSPORT_MODE) VALUES (301, 'FedEx Cargo', 'Air/Ground');

-- Products
INSERT INTO PRODUCTS (PRODUCT_ID, NAME, STOCK_QUANTITY, PRICE, SUPPLIER_ID, WAREHOUSE_ID) VALUES (1001, 'Quantum Microchip v2', 312, 149.99, 101, 1);
INSERT INTO PRODUCTS (PRODUCT_ID, NAME, STOCK_QUANTITY, PRICE, SUPPLIER_ID, WAREHOUSE_ID) VALUES (1002, 'Industrial Coolant', 120, 89.50, 102, 2);

-- Orders
INSERT INTO ORDERS (ORDER_ID, RETAILER_ID, BILL, ORDER_DATE) VALUES (5001, 201, 1499.90, SYSDATE);
INSERT INTO INCLUDE (ORDER_ID, PRODUCT_ID, ITEM_QUANTITY) VALUES (5001, 1001, 10);

-- Shipments
INSERT INTO SHIPMENT (SHIPMENT_ID, TRACKING_NUMBER, STATUS, WAREHOUSE_ID, PROVIDER_ID, ORDER_ID, SHIPMENT_TYPE) VALUES (8001, 'TRK-9876543210', 'In Transit', 1, 301, 5001, 'DAY');
INSERT INTO DAY_SHIP (SHIPMENT_ID, PREFERRED_WINDOW) VALUES (8001, 'Morning 8AM-12PM');

COMMIT;
